### ISSUE TITLE
Add Docker Support

### ISSUE THREAD

**Issue by DanBrown47** [fredysomy/pysonDB#16]
**How would this feature be useful?**
With this feature a developer can spin up a DB on the go, just few commands and pysonDB will be up and running

**Describe the solution you'd like**
Add Dockerfile, Publish to Dockerhub

**Comment by Adwaith-Rajesh** [comment]
@DanBrown47 PysonDB does not have any rest API associated with it. So having a docker image does not make sense to me. If you want pysondb inside a docker container you can directly install as you would normally install any other python package inside a container. At the end of the day I'm no the person who decides it. This is my opinion. If pysondb has an integrated API like MongoDb this is a really nice.

**Comment by fredysomy** [comment]
Hey @DanBrown47 . The easiest way is  installing it in a docker container (pip installing) for a django/flask project using the run command.

I dont think publishing a docker image of pysondb can be a feature ( i agree with every point said by @Adwaith-Rajesh )
