### ISSUE TITLE
indentation in json database file

### ISSUE THREAD

**Issue by ProgrammingPlanet** [fredysomy/pysonDB#23]
**How would this feature be useful?**
json file would be human readable in case of unable to access by this library

**Describe the solution you'd like**
optional indent parameter when creating db object

**Comment by fredysomy** [comment]
Thanks for the suggestion @ProgrammingPlanet .

**Comment by Adwaith-Rajesh** [comment]
join the discord chat [here](https://discord.gg/JxenxCfB)

**Comment by fredysomy** [comment]
Added and closing issue.

PR #25
