### ISSUE TITLE
get() method should take id of data to retrieve not count of objects to retrieve & must return singal object not array of object

### ISSUE THREAD

**Issue by ProgrammingPlanet** [fredysomy/pysonDB#24]
**How would this feature be useful?**
to get data on the bases of primary key

**Comment by fredysomy** [comment]
Yes. GetById(2838283883) will be added.

**Comment by fredysomy** [comment]
You mean , getting data by id right

**Comment by ProgrammingPlanet** [comment]
yes

but my suggestion is to name this method find(). and this method must return None when id not found and single dict object when id found.

**Comment by fredysomy** [comment]
OK. 👍

**Comment by fredysomy** [comment]
@ProgrammingPlanet #26
