### ISSUE TITLE
uniquness of id (primary key)

### ISSUE THREAD

**Issue by ProgrammingPlanet** [fredysomy/pysonDB#27]
is this library guarantee that id will always be unique?

my suggestion is to verify (after id generated) that generated key already not present in the database.

Note - it will be good if ids are started from 1 and go further like mysql auto increment column and also get track of latest id.

**Comment by Adwaith-Rajesh** [comment]
This DB uses uuid4, here is an SO answer stating its uniqueness.

> the annual risk of a given person being hit by a meteorite is estimated to be one chance in 17 billion, which means the probability is about 0.00000000006 (6 × 10−11), equivalent to the odds of creating a few tens of trillions of UUIDs in a year and having one duplicate. In other words, only after generating 1 billion UUIDs every second for the next 100 years, the probability of creating just one duplicate would be about 50%.

**Comment by fredysomy** [comment]
As long as uuid4 library guarentee the uniqueness . We also guarentee.

The generated uuid is 18 char long and has a very less chance of collisions.

**Comment by Adwaith-Rajesh** [comment]
I just stumbled upon this issue, again. here is how many unique UUID we can make with just 18 chars. This does not have connections with the DB. But just to get the idea of the possibilities. 3,570,467,226,624
