### ISSUE TITLE
suggestion: using ids as key for objects, instead of using them inside object

### ISSUE THREAD

**Issue by ProgrammingPlanet** [fredysomy/pysonDB#28]
**How would this feature be useful?**
retrieving object by its id (primary key) in O(1) times instead of O(n) time.

**Describe the solution you'd like**

currently json file looks like ---  { "data": [ { "id": 1, "k1": "v1" }, { "id": 2, "k2": "v2" }] }

it should looks like ---  { "data": { "1": {"k1": "v1"}, "2": {"k2": "v2" } } }

now we can fetch single items by its key using db["1"] in O(1) time.

**Comment by mage1k99** [comment]
great suggestion. 👍

**Comment by fredysomy** [comment]
@Adwaith-Rajesh what do you think.

**Comment by Adwaith-Rajesh** [comment]
Nice, idea but this change should be a slow one. As currently there are like 1000 ppl using this monthly so when you suddenly change how data is represented this can cause issues with ppl who does not care about the version that they are using.
But this can be useful and if we are implementing it we can also get rid of the 'data' key.

**Comment by fredysomy** [comment]
Yes. This will change the structure of data stored in db and as @Adwaith-Rajesh said. This will take some time as many projects store data in the current form and changing the structure can cause errors for them.

**Comment by fredysomy** [comment]
#31 
Thanks @Adwaith-Rajesh 

closing this now.
