### ISSUE TITLE
Use Argparse instead of Fire for CLI

### ISSUE THREAD

**Issue by fredysomy** [fredysomy/pysonDB#38]
**How would this feature be useful?**
Will help to reduce the package size.

**Describe the solution you'd like**
Using argparse

**Comment by Flodur871** [comment]
Can I work on this?

**Comment by Adwaith-Rajesh** [comment]
@Flodur871 yes offcourse. Make sure create a new branch. That it

**Comment by fredysomy** [comment]
Contributions are always welcome, do join our discord for more updates and discussions.
https://discord.gg/jyVFQtJ9yZ

**Comment by fredysomy** [comment]
Thanks for the Contribution @Flodur871 . 🥳🥳🥳
