### ISSUE TITLE
Removal of image utils

### ISSUE THREAD

**Issue by Adwaith-Rajesh** [fredysomy/pysonDB#39]
A task for the pysondb-hacktoberfest

Task details:
     Remove the imageutlls sub package and its references from the Docs

**Comment by Architrixs** [comment]
Hey, you want the [image_utils.md ](https://github.com/fredysomy/pysonDB/blob/master/docs/image_utils.md)as well as it's link from other remaining documents removed, right?
You can assign me.

**Comment by fredysomy** [comment]
And also we need to remove the imageutils code ,

Fork ,make the changes and then make PR.

Join the discord for more updates.https://discord.gg/jyVFQtJ9yZ

**Comment by fredysomy** [comment]
Thanks for the Contribution @Architrixs . See you around here.🥳

#46 merged

Closing this.
