### ISSUE TITLE
Make addMany method more effieicent

### ISSUE THREAD

**Issue by Adwaith-Rajesh** [fredysomy/pysonDB#40]
Hactoberfest - task

Issue - 

Currently the JsonStorage.addMany updates the file on every iteration of the for loop. Thus hindering performance when a large amount data is passed on to the method.

Fix - 
Move the dump function out of the for loop.

**Comment by ajratnam** [comment]
Hi, i would like to tackle this issue, can you assign this to me?

**Comment by fredysomy** [comment]
Ya sure, Do join the Discord for updates.
https://discord.gg/jyVFQtJ9yZ
Join us there
