### ISSUE TITLE
Database Export to CSV

### ISSUE THREAD

**Issue by VaishnaviNandakumar** [fredysomy/pysonDB#60]
**How would this feature be useful?**
I'd like to contribute to this feature is it's valid. This command can be used to export an existing DB into CSV format.

**Describe the solution you'd like**
A CLI command which takes in the name of the DB and the CSV file name to be exported into. 

**Describe alternatives you've considered**
Before proceeding, I wanted to know if this is a valid idea for implementation. Any other suggestions that can be used to implement this will be helpful.

**Comment by Adwaith-Rajesh** [comment]
It already exists.
https://github.com/fredysomy/pysonDB/blob/b2ef235c8dbe5dfd4640950b5dbe1abfafec3268/pysondb/cli.py#L89
in the  CLI

**Comment by Adwaith-Rajesh** [comment]
```commandline
pysondb converttocsv --help
usage: pysondb converttocsv [-h] [-t TARGET_CSV] file_name

positional arguments:
  file_name             path of the target json file

optional arguments:
  -h, --help            show this help message and exit
  -t TARGET_CSV, --target_csv TARGET_CSV
                        path of the converted csv, default : converted.csv

```

**Comment by VaishnaviNandakumar** [comment]
@Adwaith-Rajesh I didn't see it in the docs under the CLI commands. Can these be implemented in db.py?

**Comment by Adwaith-Rajesh** [comment]
The docs currently does not container most of the cli command. Will be added.

```commandline
pysondb --help
```
If you need some help

**Comment by VaishnaviNandakumar** [comment]
@Adwaith-Rajesh Hi. I wanted to know if the functions were separate for CLI and while using in a python file. I could not see any functions for conversion in `db.py`.

**Comment by Adwaith-Rajesh** [comment]
@VaishnaviNandakumar its only for the CLI for now.

You can do this 
```python
from pysondb.cli import convert_db_to_csv
```

**Comment by VaishnaviNandakumar** [comment]
@Adwaith-Rajesh Got it. Faced some issues earlier. Thanks!
